### ISSUE TITLE
Update requirements?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Gizmo#16]
Brought up here:
https://forums.adafruit.com/viewtopic.php?f=58&t=178781

New Bundle Fly feature not including the ST7789 library. That library, as well as libraries used by EInk TFT Gizmos, not in `requirements.txt`. (I think that's what bundle fly uses?)

Also, the entry in `setup.py` is `adafruit_st7789` - should that be `adafruit-circuitpython-st7789`? Or - should this library be deployed to pypi at all?

**Comment by ladyada** [comment]
doesnt have to go into pypy if it isnt yet - i think we just need to update requirements.txt to include
adafruit_il0373, adafruit_ssd1681, and adafruit_st7789
wanna do that?

**Comment by caternuson** [comment]
Sure. Question on syntax though - is it `adafruit_st7789` or `adafruit-circuitpython-st7789` that would go in `requirements.txt`? (and similar for other libraries)

**Comment by ladyada** [comment]
its whatever its called in pypi even if it isnt actually in pypi!
https://pypi.org/project/adafruit-circuitpython-st7789/

**Comment by makermelissa** [comment]
I'm pretty sure it's `adafruit-circuitpython-st7789`.
