### ISSUE TITLE
This no longer works with CircuitPython 7 or 8

### ISSUE THREAD

**Issue by empirical-dan** [adafruit/Adafruit_CircuitPython_Gizmo#25]
Incompatible .mpy file error no matter which libraries are used.
The turtle graphics program works (it accesses the driver adafruit_st7789 directly rather than via adafruit_gizmo)

**Comment by dhalbert** [comment]
Could you show a simple sample program, and the error including backtrace?

**Comment by empirical-dan** [comment]
Yes sure I will do that after work.
I used simple_test.py and get the incompatible .mpy file error on the
import from adafruit_gizmo line. Same if I use the REPL from Mu with that
line. I don't get the error message (same 8.x circuipython uf2 and library)
if I import the numbered driver directly and John Park's turtle drawing
example works.

**Comment by empirical-dan** [comment]
Sorry it was adafruit_display_text that was causing the problem in the tft_demo.py but it works now I have updated that. Strange because yesterday it was giving me an error in the REPL when trying to import adafruit_gizmo.
